version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: monobank_prod_php
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - $HOME/.composer:/home/app/.composer
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/app
    extra_hosts:
      - "database:172.17.0.1"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: monobank_prod_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
