version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: monobank_currency_bot_app_prod
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
    working_dir: /app
    volumes:
      - $HOME/.composer:/home/app/.composer
      - ./:/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: monobank_currency_bot_webserver_prod
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
