version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: monobank_php
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - $HOME/.composer:/home/app/.composer
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/app
    links:
      - mariadb
    depends_on:
      - mariadb
  nginx:
    image: nginx:alpine
    container_name: monobank_nginx
    restart: unless-stopped
    tty: true
    ports:
      - ${APPLICATION_PORT}:80
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php
  mariadb:
    image: mariadb
    container_name: monobank_mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - ${DATABASE_EXTERNAL_PORT}:3306
