version: "3.1"

services:
  php:
    build: .
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    container_name: monobank_currency_bot_php
    environment:
      APPLICATION_PORT: ${APPLICATION_PORT}
    volumes:
      - $HOME/.composer:/home/app/.composer
      - ./:/app
    user: app
    links:
      - db
    depends_on:
      - db
    entrypoint: ['php', '-S', '0.0.0.0:${APPLICATION_PORT}', 'public/index.php']
    networks:
      - app-network
  db:
    image: mariadb
    container_name: monobank_currency_bot_db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - ${DATABASE_EXTERNAL_PORT}:3306
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
